# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'Kodi Remote' do
	source 'https://github.com/CocoaPods/Specs.git'
	pod 'Alamofire', '~> 3.1.2'
	pod 'SwiftyJSON', '~> 2.3.1'
  	pod 'Box', '~> 2.0'
	pod 'Result', '0.6.0-beta.6'
  	pod 'XCGLogger', '~> 3.0'
end
